### ISSUE TITLE
Opname voor habitattype 9120

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-mhq-data#10]
9120 is een algemeen habitattype waarvoor we voldoende punten uit de VBI hebben. 

Toch werden enkele meetpunten waar 9120 werd geobserveerd (maar met ander doelhabitat) opgemeten. Zie bestand hieronder.

[check_anb_type.txt](https://github.com/inbo/n2khab-mhq-data/files/4836619/check_anb_type.txt)

**Comment by govaerle** [comment]
ok, zullen we nog eens goed moeten duidelijk maken.
Anderzijds, we hebben er extra moeten opmeten voor Patrik ikv droogte-onderzoek ;)
