### ISSUE TITLE
status_fieldwork en info_status_fieldwork nakijken voor open habitats

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-mhq-data#12]
plot 1285330, 1350866: opname is gebeurd maar info_status_fieldwork = 'Geen opname : geen toelating' 

plot 1885721: vegetatieopname is gebeurd maar info_status_fieldwork = 'Geen opname : geen doelhabitat' met opmerking doelhabitat op perceelsniveau --> nakijken of we deze plot kunnen meenemen (eventueel kan ik polsen bij Patrik)

plot 261854 en 1287030: ontbrekende status maar wel vegetatieopname gebeurd 

plot 2383474: status_fieldwork = nee en info_status_fieldwork = Geen opname : geen doelhabitat --> ofwel status_fieldwork = ja ofwel info_status_fieldwork = Geen (volledig) terreinbezoek uitgevoerd

**Comment by govaerle** [comment]
plot 1285330, 1350866: opname is gebeurd maar info_status_fieldwork = 'Geen opname : geen toelating' **ok**

plot 1885721: vegetatieopname is gebeurd maar info_status_fieldwork = 'Geen opname : geen doelhabitat' met opmerking doelhabitat op perceelsniveau --> nakijken of we deze plot kunnen meenemen (eventueel kan ik polsen bij Patrik)
**1885721 : meenemen. ik denk dat hier werd nagelaten om info status fieldwerk leeg te maken. Is databank issue volgens mij.** 

plot 261854 en 1287030: ontbrekende status maar wel vegetatieopname gebeurd **ok**

plot 2383474: status_fieldwork = nee en info_status_fieldwork = Geen opname : geen doelhabitat --> ofwel status_fieldwork = ja ofwel info_status_fieldwork = Geen (volledig) terreinbezoek uitgevoerd **is afgewerkt**
