### ISSUE TITLE
niet volledig afgewerkte boshabitatplot met status_fieldwork = 'ja'

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-mhq-data#14]
plots 121042 en 473337
status zou dus naar 'nee' veranderd moeten worden

**Comment by ToonHub** [comment]
ik zie nu een ontbrekende waarde voor 'status_fieldwork' voor plots 121042 en 473337

**Comment by govaerle** [comment]
tiens, bij mij :status_fieldwork = 2

**Comment by ToonHub** [comment]
OK foutje bij mij
