### ISSUE TITLE
duinhabitats: ontbrekende waarden voor bedekking struweelsoorten

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-mhq-data#39]
Voor een aantal plots is er voor geen enkel struweeltype een bedekking genoteerd. Het kan dan gaan om 0% bedekking of wel is men het vergeten te noteren. Daarom heb ik ook gekeken naar de bedekking van duindoorn. Ik veronderstel dat als duindoorn aanwezig is er ook minstens één struweeltype aanwezig moet zijn. 

In onderstaand bestand vind je alle plots waarvoor geen bedekking van struweeltypes zijn genoteerd, met de bedekking van duindoorn.
 
[struweelsoorten_missing.csv](https://github.com/user-attachments/files/16846828/struweelsoorten_missing.csv)

Als duindoorn niet aanwezig is: aantal struweelsoorten = 0
Als duindoorn aanwezig is in struiklaag: aantal struweelsoorten = NA
Als duindoorn enkel aanwezig is in kruidlaag?

**Comment by Patrikoosterlynck** [comment]
Dag Toon,
ik heb de problemen nagekeken.
Merendeel is te wijten aan één waarnemer die deze meting vergat in te voeren in de periode 2022 tot gisteren.
Dan zjn er wel nog een aantal andere records waar je blijkbaar de data hebt meegenomen maar waarvoor de plot niet is bemeten. Er is wel altijd sprake van een aandeel 2160 in de plot, maar de meting is gebeurd voor een ander target-type. Dit zit juist in de mhq sheet. Waarschijnlijk heb jij die mee obv inboveg$habitat waar soms een complex genoteerd is.  Indien dit het geval si toch beter even koppelen met die mhq waarin naast target-type ook het effectief bemeten type genoteerd is
[struweelsoorten_missing_PO.csv](https://github.com/user-attachments/files/16870357/struweelsoorten_missing_PO.csv)

Zie bijlage voor details

**Comment by Patrikoosterlynck** [comment]
En ik denk dat wanneer de data voor struweeltype ontbreekt dat we die niet kunnen afleiden 
Inderdaad met duindoorn minstens 1 tpye maar het kunnen er ook meer zijn, dus NA

**Comment by ToonHub** [comment]
Bedankt om na te kijken.

Ik heb inderdaad eerst per meetpunt LSVI berekend voor alle geobserveerd habitattypes (puur op basis van inboveg gegevens). Daarna selecteer ik de berekening voor het habitattype waarvoor opname is uitgevoerd (op basis van mhq opvolginstabel).

De ontbrekende waarde voor de plots die deels 2160 bevatten maar voor voor de opname voor ander habitat gebeurd zijn vormen dus geen probleem.

De andere ontbrekende waarden zijn dan NA's.

**Comment by Patrikoosterlynck** [comment]
Bestaat dan niet de mogelijkheid dat we potentiële fouten maken dooralles te berekenen wat genoteerd is in het complex?
Lijkt me beter om eerst te selecteren op type waarvoor de opname is uitgevoerd.
