### ISSUE TITLE
plot 201689 segment 2: 91E0_vc --> geen habitat

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-mhq-data#5]
landuse geeft aan dat dit een poel is. Dus habitattype 91E0_vc veranderen naar 'geen habitat'

**Comment by govaerle** [comment]
deze plot is deels 91E0_vc en deels poel. Voor het stukje poel is habt aangepast naar geen habitat. De opname valt in het stuk 91E0_Vc (IDSegment in Vegetation = 1)

**Comment by ToonHub** [comment]
OK
