### ISSUE TITLE
boshab : plots met twee paar coördinaten + plot met verkeerde coördinaten

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-mhq-data#7]
er zijn 3 boshabitatplots met elk 2 paar coördinaten en één plot met extreem hoge waarden voor de coördinaten
[check_coordinates_anb.txt](https://github.com/inbo/n2khab-mhq-data/files/4835512/check_coordinates_anb.txt)

**Comment by govaerle** [comment]
opgelost

**Comment by ToonHub** [comment]
voor plot 12710 zie ik nog steeds twee paar coördinaten. De andere punten zijn OK.
De correcte coördinaten heeft als x 190270.509

**Comment by govaerle** [comment]
Deze navplot is opnieuw naar ALex om 2 laatste punten af te werken. Wanneer hij klaar is delete ik in de bijgewerkte navplot het overtollige punt (gemakkelijk te herkennen : is punt centraal in Vlaanderen gelegen).

**Comment by govaerle** [comment]
opgelost
