### ISSUE TITLE
verplaatsen van meetpunten

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-mhq-data#8]
Ik weet niet precies wat er afgesproken is met Patrik over het verplaatsen van punten en wat hierover in het veldprotocol staat. Maar ik zie dat er heel wat punten verplaatst werden: ongeveer 140 over een afstand van minstens één meter; 70 over een afstand van minstens 5 meter.

De maximale afstand die we toelaten is 100 meter. Vier plots werden over een grotere afstand verplaatst. Zie bestand hieronder.
Vier plots werden verplaats, maar werden uiteindelijk niet opgemeten want geen habitat. 

[check_distance_anb.txt](https://github.com/inbo/n2khab-mhq-data/files/4835625/check_distance_anb.txt)

**Comment by ToonHub** [comment]
al kort besproken op overleg, maar gewoon ter info een overzicht van de verplaatste punten

**Comment by govaerle** [comment]
bedankt, gecheckt en al deze plots zijn opgemeten door dezelfde persoon. Nu weet ik wie in te lichten dat hier moet voor opgelet worden.
